name: kmindustrial
description: A minimal Flutter app scaffold created manually.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.10
  intl: ^0.18.1
  mobile_scanner: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/km_ind_1024.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/km_ind_1024.png"
